# -*- coding: utf-8 -*-
"""Backpropagation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lfdXRGBzb6DooNaiSwO6SwzEtjL7lNPp
"""

import torch

x = torch.tensor(5.0)
y = torch.tensor(8.0)

w = torch.tensor(5.0, requires_grad=True)

#Forward pass and compute loss
y_hat = w * x
loss = (y_hat - y)**2
print(loss)

#Backward Pass
loss.backward()
print(w.grad)

