# -*- coding: utf-8 -*-
"""Linear_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16ZBYSg81QmTVgAI4x0l2holZENvjVeJv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

df = pd.read_csv('/content/houseprice.csv')
df

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area(sqr ft)')
plt.ylabel('price(US$)')
plt.scatter(df.area, df.price, color = 'red', marker = '+')

reg = linear_model.LinearRegression()
reg.fit(df[['area']], df.price)

reg.predict([[3300]])

reg.coef_

reg.intercept_

# y = m*x+b  Formula
#135.78767123*3300+180616.43835616432

reg.predict([[3300]])

import pickle

with open('model_pickle', 'wb') as f:
  pickle.dump(reg,f)

with open('model_pickle', 'rb') as f:
  mp = pickle.load(f)

mp.predict([[5000]])

