# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1adiHnCIrj0ug_OFw0wM54jCZXXULIyLb
"""

!pip install torch torchvision

import torch

import torch.nn as nn

input_tensor = torch.tensor([[6.0]])

sigmoid = nn.Sigmoid()

output = sigmoid(input_tensor)

model = nn.Sequential(
    nn.Linear(6,4),
    nn.Linear(4,1),
    nn.Sigmoid()
)

#Creating Input Tensor

input_tensor = torch.tensor(
    [[4.3, 6.1, 2.3]]
)

#Apply Softmax with the last dimension
probabilities = nn.Softmax(dim = -1)
output_tensor = probabilities(input_tensor)

print(output_tensor)

