# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_sc1y7nQdUSA3z5qLmzJqo9PvnI3GgAC
"""

import pandas as pd
import numpy as np
from sklearn import linear_model

df = pd.read_csv('/content/multivariatvariable.csv')
df

df.bedrooms.median()

reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

reg.coef_

reg.intercept_

reg.predict([[3600, 3 , 40]])

